### PR TITLE
Basic Personal Amount

### LINKED ISSUE #151: Canada Basic personal amount
[Source](https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/federal-government-budgets/basic-personal-amount.html)

### PR DESCRIPTION
**Pull request by PavelMakarchuk**
Fixes #151

### CODE REVIEW

**Comment by MaxGhenis** [comment]
It looks like there's a dependent element too is that right? Want to save that for a separate PR if so?

**Comment by PavelMakarchuk** [comment]
> It looks like there's a dependent element too is that right? Want to save that for a separate PR if so?

**Comment by PavelMakarchuk** [comment]
> > It looks like there's a dependent element too is that right? Want to save that for a separate PR if so?

**Comment by PavelMakarchuk** [comment]
> > > It looks like there's a dependent element too is that right? Want to save that for a separate PR if so?

I should put it into this PR

**Comment by PavelMakarchuk** [comment]
> It looks like there's a dependent element too is that right? Want to save that for a separate PR if so?

I will put it into a separate PR "Spouse or common-law partner amount"

**Review by MaxGhenis — APPROVED** [review]
could you just remove the todo comments? please move to issues as needed

**Pull request merged**
